#### Stocks data

In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('stocks.csv')
df.head()

  outlet_id  product_id  quantity
0      ST01        2075        218
1      ST02        4652        131
2      ST01        1395        209
3      ST03         983        264
4      ST02        1021        249

In [20]:
df.duplicated().any()

False

In [11]:
df = df.drop_duplicates()

In [21]:
df.shape

(4328, 3)

In [13]:
df.duplicated().any()

False

In [14]:
df.head()

  outlet_id  product_id  quantity
0      ST01        2075        218
1      ST02        4652        131
2      ST01        1395        209
3      ST03         983        264
4      ST02        1021        249

In [23]:
for row in df.iterrows():
    print(f"INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)\n\tVALUES('{row[1][0]}', {row[1][1]}, {row[1][1]});")

INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 2075, 2075);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4652, 4652);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 1395, 1395);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 983, 983);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 1021, 1021);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 327, 327);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2516, 2516);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 2298, 2298);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 1220, 1220);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4410, 4410);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4542, 4542);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2015, 2015);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2364, 2364);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 702, 702);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4886, 4886);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 654, 654);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 157, 157);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 397, 397);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 1449, 1449);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3642, 3642);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 97, 97);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4428, 4428);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 2481, 2481);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3856, 3856);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4159, 4159);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4895, 4895);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 1815, 1815);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3763, 3763);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3027, 3027);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1564, 1564);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1434, 1434);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3095, 3095);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4639, 4639);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 2816, 2816);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3195, 3195);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4927, 4927);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3529, 3529);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4480, 4480);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1413, 1413);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3388, 3388);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 2295, 2295);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4239, 4239);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 717, 717);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 2844, 2844);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3563, 3563);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3862, 3862);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 827, 827);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 995, 995);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 1985, 1985);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 472, 472);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1278, 1278);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 468, 468);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4726, 4726);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 46, 46);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1884, 1884);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4819, 4819);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 1336, 1336);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3614, 3614);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2456, 2456);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2435, 2435);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4017, 4017);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2734, 2734);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 2791, 2791);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4792, 4792);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 2082, 2082);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 135, 135);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1540, 1540);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3660, 3660);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4243, 4243);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3698, 3698);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3244, 3244);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3114, 3114);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4933, 4933);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4545, 4545);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1466, 1466);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2365, 2365);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 34, 34);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2244, 2244);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 907, 907);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3833, 3833);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4380, 4380);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4088, 4088);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 162, 162);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 1360, 1360);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1885, 1885);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3461, 3461);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4993, 4993);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4058, 4058);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2743, 2743);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 90, 90);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3491, 3491);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 17, 17);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4912, 4912);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 240, 240);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1496, 1496);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 485, 485);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 3572, 3572);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3562, 3562);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2603, 2603);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 750, 750);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3622, 3622);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 667, 667);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 898, 898);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 210, 210);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4303, 4303);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1568, 1568);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 2845, 2845);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2499, 2499);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 401, 401);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 3476, 3476);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 1705, 1705);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 499, 499);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 204, 204);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3701, 3701);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2912, 2912);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2825, 2825);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 15, 15);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4962, 4962);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 375, 375);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4077, 4077);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3409, 3409);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3702, 3702);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 407, 407);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 2197, 2197);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 227, 227);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 171, 171);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4237, 4237);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 4011, 4011);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST02', 282, 282);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 931, 931);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 22, 22);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 1176, 1176);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 4391, 4391);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST01', 4823, 4823);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 3066, 3066);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3428, 3428);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST04', 474, 474);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 237, 237);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2039, 2039);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3605, 3605);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1638, 1638);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2255, 2255);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4829, 4829);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1304, 1304);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 951, 951);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 109, 109);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1282, 1282);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 364, 364);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1065, 1065);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2409, 2409);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2353, 2353);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4053, 4053);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4251, 4251);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 289, 289);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 448, 448);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2142, 2142);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3548, 3548);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4117, 4117);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4949, 4949);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3573, 3573);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 565, 565);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 259, 259);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4510, 4510);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3523, 3523);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1710, 1710);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3301, 3301);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2887, 2887);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3747, 3747);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1657, 1657);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2670, 2670);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1811, 1811);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2884, 2884);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4850, 4850);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 921, 921);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1543, 1543);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 880, 880);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4735, 4735);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3494, 3494);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3468, 3468);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2265, 2265);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 80, 80);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4215, 4215);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 99, 99);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2328, 2328);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2526, 2526);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 134, 134);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 402, 402);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2648, 2648);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 873, 873);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2268, 2268);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2668, 2668);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2281, 2281);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4487, 4487);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2040, 2040);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1535, 1535);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 84, 84);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2590, 2590);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2538, 2538);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3510, 3510);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2671, 2671);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2880, 2880);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 594, 594);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2596, 2596);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 395, 395);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3662, 3662);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2206, 2206);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3215, 3215);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1829, 1829);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3458, 3458);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 1313, 1313);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4107, 4107);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2525, 2525);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 2632, 2632);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 4950, 4950);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3068, 3068);
INSERT INTO HyperMarket.stocks(outlet_id, product_id, quantity)
	VALUES('ST03', 3257, 3257);